import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home({ car }) {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Car Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={car.image} />
      </Head>

      <main className={styles.main}>
        <button onClick={() => router.push("/cars")}>See Cars!!</button>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const req = await fetch("http://localhost:3000/tesla.json");

  const data = await req.json();

  return {
    props: {
      car: data,
    },
  };
}
